account/urls.py
# リスト4-31:新規作成。4.6.1 ユーザ認証のテスト実装、手順6:アプリケーションaccountのurls.pyの新規作成
# 
from django.urls import path
from account.views import MyLoginView, MyLogoutView, TopView

app_name = "account"
 
urlpatterns = [
    path("", TopView.as_view(), name = "top"),
    path("login/", MyLoginView.as_view(), name = "login"),
    path("logout/", MyLogoutView.as_view(), name = "logout"),
]

datashare/urls.py
# リスト3-3:datashare/urls.py
from django.urls import path
from . import views

app_name = "datashare"

urlpatterns = [
    # viewsの関数indexを紐付ける
    path(
        "", views.index, name="index"
    ),
    # リスト3-6:追加。viewsの関数mypageを紐付ける
    path(
        "mypage/", views.mypage_funView, name="mypage"
    ),
    # リスト3-14:追加。viewsの関数ではなくクラスであるので、frmPublishView.as_view()の記述でフォーラムクラスと紐付ける。
    path(
        "frmPublish/", views.frmPublishView.as_view(), name="frmPublish"
    ),
    # リスト4-14:追加。4.5.1 情報表示とファイルとダウンロードの機能実装、手順2:アプリdatashareのurls.pyの記述追加
    path(
        "mypage_db/", views.mypage_dbView.as_view(), name="mypage_db"
    ),
    # リスト4-18:追加。4.5.2 情報発信とファイルァップロードの機能実装、手順3:アプリdatashareのurls.pyの記述追加
    path(
        "publish_db/", views.publish_byModelfrmView, name="publish_db"
    ),
    # リスト4-22:追加。4.5.3 情報更新と削除の機能実装、手順2:アプリdatashare/urls.pyへの記述追加
    path(
        "edit/<int:num>", views.edit, name="edit"
    ),
    # リスト4-38:追加。4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順4:
    # リスト4-38の行13と行14は、それぞれMyLoginViewとMyLogoutViewに対し、URLとビュークラスの紐付けを設定する。
    path(
        "login/", views.MyLoginView.as_view(), name = "login"
    ),
    path(
        #"logout/", views.MyLogoutView.as_view(), name= "logout"
        "logout/", views.MyLogoutView.as_view(), name= "logout"
    ),
]

project_gis/urls.py
# リスト4-9:project_gis/urls.py
from django.conf import settings  # リスト4-9:追加
from django.conf.urls.static import static  # リスト4-9:追加

# (2)手順2:ルーティングproject_gis/urls.pyの作成
from django.contrib import admin
from django.urls import path, include  # リスト3-2:includeを追加

urlpatterns = [
    path("admin/", admin.site.urls),
    path("datashare/", include("datashare.urls")),  # リスト3-2:追加
    path("account/", include('account.urls'))       # リスト4-28:追加。4.6.1 ユーザ認証のテスト実装、手順3:アプリケーションaccountへのpathを追加する
]

# 4.4.3 モデルのデータベース実装、手順2:ルーティングファイルヘの追記項目
# リスト4-9:追加。MEDIA_URLとMEDIA_ROOTへの紐付けを設定する。
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

datashare/models.py
# リスト4-6:datashare/models.py:pythonクラスとしてモデルを定義する。
from django.db import models
from django.contrib.auth.models import User, Group

# モデルpub_messageは、Djangoモデルクラスmodels.Modelを継承している。5つのフィールドを定義する。
# フィールドsenderは、外部キーフィールド(models.Foreign Key)として、Userテープルと関連付ける。
# 同じ方法で、フィールドprojectも外部キーとして、Groupテープルをつなぐ)。そのために、UserとGroupのモデルは、予めインプットしておく。
# フィールドsend_messageはmodels.CharFieldを用いて、文字列フィールドとして定義する。
# フィールドsend_documentはファイルアップロードをするために、models.Filefieldを使って定義する。
# 最後のsend_dateは投稿H付を保存するために、models.Date1Timeを用いて定義する。
class pub_message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Group, on_delete=models.CASCADE)
    send_message = models.CharField(max_length=1000)
    send_document = models.FileField(upload_to="documents/")
    send_date = models.DateTimeField(auto_now_add=True)

datashare/forms.py
# リスト3-12:datashare/templates/datashare/forms.py
from django import forms
from .models import pub_message  # リスト4-16:追加

# リスト4-36:追加。ログインフォームクラスLoginForm()を定義する
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

# django.forms.Formクラスを継承し、フォームクラスfrmPublishを定義する。
# Djangoのフォームクラスを定義する構文の基本構造
# classフォームクラス名(forms.Form)
#     事前処理コード
#
#     変数名1 = forms.フィールドクラス1(引数1, 引数2, ...）
#     変数名2 = forms.フィールドクラス2(引数1, 引数2, ...）
#     ...
class frmPublish(forms.Form):
    PROJECTS = (
        ("1", "地域防災関連"),
        ("2", "都市計画関連"),
        ("3", "地壌産婁関運"),
    )
    # 3つのコンポーネント(部品)をform field classを用いて定義する。
    # 氏名を記述するtextbox:forms.CharFieldOのフィールドクラスを用いて定義し、変数nameに保存する。
    name = forms.CharField(label="Name", max_length=50)
    # 関辿プロジェクトを選択するためのdropdown list:変数projectとforms.ChoiceFeildOを用いて定義する。
    project = forms.ChoiceField(label="Project", choices=PROJECTS)
    # 、投稿メッセージを記入するためtextarea:forms.CharFieldOで定義し、引数widget=forms.Textareaを川いてテキストエリアを指定する。そのフィールドクラスは変数contentsで保仔される。
    contents = forms.CharField(label="Message", widget=forms.Textarea)


# リスト4-16:追加。
class frmModelPublish(forms.ModelForm):
    class Meta:
        model = pub_message
        fields = ["sender", "project", "send_message", "send_document"]

# リスト4-36:追加:4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順1:リスト4・299:accoun1/forms.pyのように、ログインフォームクラスLoginForm()を定義する
class LoginForm(AuthenticationForm):
    class meta:
        model = User
        fields = ['username', 'password']

datashare/views.py
from django.shortcuts import redirect, render  #  リスト4-13:redirect追加
from datashare.forms import (
    frmPublish,
    frmModelPublish,
)  # リスト4-13:frmModelPublish追加 # リスト3-13:追加

from django.contrib.auth.mixins import LoginRequiredMixin   # リスト4-37:追加

from django.views.generic import TemplateView  # リスト3-13:追加。
from .models import pub_message  # リスト4-13:追加。、モデルpub_messageをインポートする。
# from .forms import frmModelPublish  # リスト4-17:追加

from .forms import frmModelPublish, LoginForm               # リスト4-37:追加
from django.contrib.auth.views import LoginView, LogoutView # リスト4-37:追加


def index(request):
    parmas = {
        "title": "地理空間情報の共有サイト",
        "msg": "これはトッブページです。",
        "goto_mypage": "datashare:mypage",  # リスト3-5:追加
    }
    return render(request, "datashare/index.html", parmas)


# リスト3-5:追加
def mypage_funView(request):
    parmas = {
        "title": "地理空間情報の共有サイト",
        "msg": "これはマイページです。",
        "goto_index": "datashare:index",
    }
    return render(request, "datashare/mypage.html", parmas)

# リスト3-13:datashare/views.py:56-75
# フォームクラスを処理するためのPythonクラスdjango.views.genericのビュークラス(view class:TemplateView)を使う。
# ビュークラスは、TemplateViewクラスを継承し、フォームクラスを処理する。
# ビュークラスの基本構造
# class クラス名(TemplateView):
#     def __init__(self): # 初期関数を定義し、必要があれば事前処理を行う。
#         [事前処理]
#
#     def get(self, ...)
#         関数getを定義し、フォームが最初に呼び出されるときの処理を行う。
#     def post(self, ...)
#         関数postを定義し、ユーザがフォームに何らかの情報を記述し、フォームが再びpostbackされたときの処理を行う。
# frmPublishViewクラスを追加する
class frmPublishView(TemplateView):
    def __init__(self):
        self.parmas = {
            "title": "地理空間情報の共有サイト",
            "msg": "これは、投稿ページです。",
            "form": frmPublish(),
            "answer": None,
            "goto_index": "datashare:index",
        }

    def get(self, request):
        return render(request, "datashare/frmPublish.html", self.parmas)

    def post(self, request): # ユーザがフォームに記述した情報requestを取得する。
        person = request.POST["name"]
        proj = request.POST["project"]
        cont = request.POST["contents"]
        # ユーザの回答を編集し、変数parmas['answer']へ渡す。
        self.parmas["answer"] = (
            "name=" + person + ", project=" + proj + ", contents=" + cont + "."
        )
        # フォームフィールドに記述情報が残されたままの状態で、フォームfrmPublish()を変数parmas['form']へ渡す。
        self.parmas["form"] = frmPublish(request.POST)
        # こうしたユーザ記述した惜報self.parmasをもう一度テンプレートのfrmPublish.htmlに送る。
        return render(request, "daashare/frmPublish.html", self.parmas)


# 4.5.1 情報表示とファイルとダウンロードの機能実装、手順1:アプリdatashareのviews.pyの記述追加
# リスト4-13:新規作成。クラスTemplateView継承したビュークラスmypage_dbViewを定義する。
# リスト3-13のクラスfrmPublishView()にもTemplateView継承したビュークラスを作成したが、今回のリスト4-13のクラス構造とは異なる。
# リスト3-13は、フォームと連動した動的な配信を対応するビュークラスであり、getとpostの2つの配信状態を踏まえ、
# __init__()、get()とpost()、3つの関数を設けた。
# それに対し、リスト4-13は、(1)モデルとの連動、(2)get関数による梢報収集のみであり、post関数による1青報の配信はない。
#
# リスト4-37:追加修正。4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順2:
# リスト4-30:accoun1/vicws.pyを参照し、datashare/views.pyに値する修正と追加を行った。
# まず、ユーザ認証に必要なフォームクラス、モデルとコンポーネントをインポートする(行3、行6と行7)。
# 次は、マイページmypage_dbViewに対し、
#
# ①ユーザ認証LoginRequiredMixinの記述追加(行27)、
# ②ログインが成功したとき、ユーザ情報の取得(行32)、
# ③ログアウトページヘのリンク追加(行38)、
#
# 3つの追加記述を行う。
# class mypage_dbView(TemplateView):
class mypage_dbView(LoginRequiredMixin, TemplateView): # リスト4-37:追加修正
    # 紐付け先mypage_db.htmlのパスを明記する。
    template_name = "datashare/mypage_db.html"

    # データベースからデータの取得は、Djangoが用意したget_context_data()関数を利用する。
    # 親クラスから辞書型の引数**kwargsを持つget_context_data()関数を継承し、
    # 次のオーバーライド作業により、様々な情報を変数contextに渡す。
    # 行33では、pub_message.objects.all()を用いて、テープルpub_messageからすべてのデータを抽出し、その結果を
    # ["pub_message_list"] と名づけ、辞書型変数context["pub_message_list"]に渡す。
    # 次の行35～行37は、ページmypage_db.htmlに表示したい情報や、トップページindexへの名前空間URLを変数contextに渡す。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user               # リスト4-37:追加
        context["pub_message_list"] = pub_message.objects.all().order_by("id")

        context["title"] = "地理空間データの共有サイト"
        context["msg"] = "これはマイページ(DB接続)です"
        # リスト4-37:修正
        # context["goto_index"] = "datashare:index"
        context["goto_publish_db"] = "datashare:publish_db"
        # リスト4-37:追加
        context["goto_logout"] = "datashare:logout"

        return context


# リスト4-17:追加。4.5.2情報発信とファイルァップロードの機能実装、手順1:アプリdatashareのforms.pyの記述追加
def publish_byModelfrmView(request):
    if request.method == "POST":
        form = frmModelPublish(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("datashare:mypage_db")
        else:
            form = frmModelPublish()

    parmas = {
        "title": "地理空間情報の共有サイト",
        "msg": "これは投稿サイトです。",
        "form": frmModelPublish(),
        "goto_mypage_db": "datashare:mypage_db",
    }
    return render(request, "datashare/publish_db.html", parmas)


# リスト4-21:新規追加。4.5.3 情報更新と削除の機能実装、手順1:アプリdatashare/views.pyへの記述追加
def edit(request, num):
    obj = pub_message.objects.get(id=num)
    if request.method == "POST":
        if "btn_update" in request.POST:
            form = frmModelPublish(request.POST, instance=obj)
            form.save()
            return redirect("datashare:mypage_db")
        elif "btn_delete" in request.POST:
            obj.delete()
            return redirect("datashare:mypage_db")
        elif "btn_back" in request.POST:
            return redirect("datashare:mypage_db")

    parmas = {
        "title": "地理空間情報の共有サイト",
        "msg": "これは投稿の編集サイトです。",
        "id": num,
        "form": frmModelPublish(instance=obj),
    }

    return render(request, "datashare/edit.html", parmas)

# リスト4-37:追加修正。4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順2:
# 行98～行103の記述は、リスト4-30:accoun1/vicws.pyと同様、それぞれログインページとログアウトページヘの紐付けを設定する。
class MyLoginView(LoginView):
    form_class = LoginForm
    template_name = "datashare/login.html"

class MyLogoutView(LogoutView):
    template_name = "datashare/logout.html"

datashare/templates/datashare/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <h1>{{ title }}</h1>
        {% block contents %}{% endblock %}
    </body> 
</html> 

<!-- リスト3-9:datashare/base.html -->

datashare/templates/datashare/edit.html
{% extends 'datashare/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block contents %}
    <p>{{ msg }}</p>
    <p>{{ answer|safe }}</p>
    <form action="{% url 'datashare:edit' id %}" method="post">
        {% csrf_token %}
        <p>ID = {{id}}</p>
        <table>
            {{ form.as_table }}
            <tr><th><td> 
                <input type="submit" value=“更新" name="btn_update">
                <input type="submit" value=“削除" name="btn_delete">
                <input type="submit" value=“戻る" name="btn_back">
            </td></th></tr>
        </table>
    </form>
{% endblock %}

<!-- リスト4-24:新規作成。4.5.3 情報更新と削除の機能実装、手順手順4:e dit.htmlの新規作成
 

datashare/templates/datashare/frmPublish.html
{% extends 'datashare/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block contents %}
    <p>{{ msg }}</p>
    <p>{{ answer | safe }}</p> 
    <!-- 変数answerの情報をHTMLに書き出すとき、行5のタグ名<p>~</p>も含めて書き出すように指示する。-->
    <!-- つまり、HTML上の表示形式を保つために、変数answerの値とHTMLのタグを同時に書き出す-->

    <!-- form送信先の指定、ここでは名前空間を用いたURL -->
    <form action="{% url 'datashare:frmPublish' %}" method="post">
        <!-- 大量の偽造リクエストによるWebフォームヘの攻撃を防ぐための措置。セキュリティ上欠かせない大事な記述項目。-->
        {% csrf_token %}
        
        <!-- formの項目を成形しながら表示する -->
        <table> 
            <!-- ormのフィールドをテープルのように成形し表示する-->
            {{ form.as_table }}
           <tr>
               <td></td>
               <td><input type="submit" value="投稿"></td>
           </tr> 
       </table> 
    </form> 
    <p><a href="{% url goto_index %}">Indexへ戻る</a></p>
{% endblock %}

<!-- リスト3-15:datashare/templates/datashare/frmPublish.html -->

datashare/templates/datashare/index.html
{% extends 'datashare/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block contents %}
    <p>{{ msg }}</p>
    <p><a href="{% url 'datashare:mypage' %}">My Pageへ</a></p>
    <p><a href="{% url 'datashare:frmPublish' %}">投稿Pageへ</a></p>
    <p><a href="{% url 'datashare:mypage_db' %}">My Pageへ(DB接続)</a></p>
    <!-- リスト4-15:追加 -->
{% endblock %}

<!-- リスト3-10:datashare/templates/datashare/index.html -->
    <!--<p><a href="{% url goto_mypage %}">My Pageへ</a></p>-->
    <!--<p><a href="{% url goto_mypage_db %}">MyPageへ(DB接続)</a></p>-->
    <!--<p><a href="{% url goto_frmPublish %}">投稿Pageへ</a></p>-->

datashare/templates/datashare/login.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>Login to MyPag</title>
    </head>

    <body>
        <h1>地理空間情報の共有サイト</h1>
        <h1>Login to MyPage</h1>
        <form action="", method="post">
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field }}
                {{ field.errors }}
                <br>
            {% endfor %}
            <button type="submit">Login</button>
            <input type="hidden" name="nest" value="{{nest}}" />
            {% csrf_token %}
       </form>
    </body>
</html>


<!-- # リスト4-39:新規作成。4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順4: -->
<!-- 基本的には、リスト4-344:account/login.htmlと同じlogin.htmlを記述している。 -->
<!-- 行10～行16は、for文を使用し、フォームの項目を順番に表示する。 -->
<!-- for文の上に{{ form.non_field_errors }}という記述があるが(行11)、これは特定のフィールドに紐づかないエラーを表示するための記述である。 -->
<!-- エラーメッセージは、行14で表示している。 -->

<!-- # リスト4-39:新規作成。4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順5: -->
<!-- マイページmypage_db.htmlには、ユーザ1情報表示の追加(行4)、ログアウトページヘのリンク追加(行27)だけを加えた(リスト4-40)。 -->

datashare/templates/datashare/logout.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>Login to Top Pag</title>
    </head> 

    <body>
        <p>ログアウトしました</p>
        <p>ありがとうございました。</p>
        <p><a href="{% url 'datashare:index' %}">Back to Index</a></p>
    </body>
</html>

<!-- 4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順4:関連のHTMLページの作成と修正 -->
<!-- 最後のログアウトページヘlogout.htmlには、簡単なメッセージとindex.htmlへのリンクを記述した(リスト4・41)。 -->

datashare/templates/datashare/mypage.html
{% extends 'datashare/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block contents %}
    <p>{{ msg }}</p>
    <p><a href="{% url goto_index %}">Indexへ戻る</a></p>
{% endblock %}

<!-- リスト3-11:datashare/templates/datashare/mypage.html -->
    <!--<p><a href="{% url 'datashare:frmPublish' %}">投稿Pageへ</a>
        <a href="{% url goto_mypage_db %}">MyPageへ(DB接続)</a></p> リスト4-15:追加 -->

datashare/templates/datashare/mypage_db.html
{% extends 'datashare/base.html' %}
{% block title  %}{{ title }}{% endblock %}
{% block contents %}
    <!-- <p>{{ msg | safe }}</p> -->
    <p>これは{{ user.username | safe }}のサイトです(DB接続)。</p>
    <table border="1" style="border-collapse: collapse; border-color: ■000000">
        <tr>
            <th>ID</th>
            <th>Sender</th>
            <th>Project</th>
            <th>Message</th>
            <th>Document</th>
            <th>Date</th>
        </tr>
    {% for item in pub_message_list %}
        <tr>
            <!-- リスト4-23:修正。4.5.3 情報更新と削除の機能実装、手順3:mypage_db.htmlの修正 -->
            <td><a href="{% url 'datashare:edit' item.id %}">Edit ID = {{ item.id }}</a></td>
            <td>{{ item.sender }}</td>
            <td>{{ item.project }}</td>
            <td>{{ item.send_message }}</td>
            <td><a href="http://localhost:8000/media/{{ item.send_document }}">
                {{ item.send_document }}</a></td>
            <td>{{ item.send_date }}</td>
        </tr> 
    {% endfor %}
    </table>
    <!-- リスト4-19:修正。4.5.2 情報発信とファイルァップロードの機能実装、手順4:mypage_db.htmlの修正とpublish_db.html新規作成 -->
    <p><a href="{% url goto_publish_db %}">投稿サイトへ(DB接続)</a>
       <a href="{% url goto_logout %}">Logoutへ</a></p>
{% endblock %}

<!--   <form method="post" action="{% url 'datashare:logout' %}"></form>
    {% csrf_token %}
    <button type="submit">Logoutへ</button>-->

       <!-- <a href="{% url 'datashare:index' %}">Indexへ戻る</a></p> -->
       <!--<a href="{% url goto_logout %}">Logoutへ</a></p>-->
<!-- 4.5.1 情報表示とファイルとダウンロードの機能実装、手順3:アプリdatashareのmypage_db.htmlの
新規作成 -->
<!-- リスト4-15:templates/datashare/mypage_db.html -->
<!--    <p><a href="% url goto_publish_db %">投稿サイトへ(DB接続)</a>  -->
<!--       <a href="% url goto_index %">Indexへ戻る</a></p> -->
<!-- 4.6.2 アプリケーションdatashareにおけるユーザ認証機能の実装、手順4:関連のHTMLページの作成と修正 -->
<!-- マイページmypage_db.htmlには、ユーザ1情報表示の追加(行4)、ログアウトページヘのリンク追加(行27)だけを加えた(リスト4-40)。 -->

datashare/templates/datashare/publish_db.html
{% extends 'datashare/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block contents %}
    <p>{{ msg }}</p>
    <p>{{ answerlsafe }}</p>
    <form enctype="multipart/form-data"
        action="{% url 'datashare:publish_db' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" value="投稿"></td>
            </tr>
        </table>
    </form>
    <p><a href="{% url goto_mypage_db %}">My Pageに戻る(DB接続)</a></p>
{% endblock %}

<!-- リスト4-20:修正。4.5.2 情報発信とファイルァップロードの機能実装、手順4:mypage_db.htmlの修正とpublish_db.html新規作成 -->